**TEST DATA**

---


This notebook unvails suspected errors in the test (test_raw.csv) dataset

**Please note that the 'Original_Index' column was started from 1 not 0**

In [1]:
import pandas as pd

# 1. Load the original CSV
df = pd.read_csv('/content/test_raw.csv')

# 2. Keep only the three columns you care about
df_selected = df[['Master_Index', 'Prompt',]]

In [3]:
# 3. List of row‐numbers (1‑based)
keep_1_based = [3,9,15,18,19,21,22,23,30,32,33,38,39,43,69,74,75,78,79,82,83,88,89,91,99]

In [4]:
# 4. Convert to 0‑based positions for .iloc
keep_0_based = [i - 1 for i in keep_1_based]

# 5. Extract those rows (copying to avoid SettingWithCopyWarning)
df_filtered = df_selected.iloc[keep_0_based].copy()

# 6. Add a new column “Original_Index” that reflects the 1‑based row number
df_filtered['Original_Index'] = keep_1_based

# 7. Reorder columns so that Original_Index comes first
df_filtered = df_filtered[['Original_Index', 'Master_Index', 'Prompt', ]]

In [5]:
#8. Print dataframe
df_filtered

,Original_Index,Master_Index,Prompt
2,3,ID_TYHSA,I am a nurse working in a National Referral Ho...
8,9,ID_UFAFI,I am a nurse working in a Sub-county Hospitals...
14,15,ID_OTEWX,I am a nurse with 16 years of experience in Ca...
17,18,ID_ZQLND,I am a nurse with 22 years of experience in Ge...
18,19,ID_LXBDD,I am a nurse with 15 years of experience in Ge...
20,21,ID_VJVBS,I am a nurse working in a National Referral Ho...
21,22,ID_OZCVT,I am a nurse working in a National Referral Ho...
22,23,ID_HBKUL,I am a nurse with 1 years of experience in Gen...
29,30,ID_LWSTJ,I am a nurse with 16 years of experience in Ge...
31,32,ID_NTHZR,I am a nurse with 16 years of experience in Ge...
32,33,ID_UAHZM,I am a nurse with 18 years of experience in Ge...
37,38,ID_ZNYCZ,I am a nurse with 10 years of experience in Ge...
38,39,ID_NCNYB,I am a nurse with 27 years of experience in Ge...
42,43,ID_JADVZ,I am a nurse with 22 years of experience in Ge...
68,69,ID_SKCAI,I am a nurse with 23 years of experience in Ge...
73,74,ID_BFBYN,I am a nurse with 1 years of experience in Gen...
74,75,ID_EISIY,I am a nurse with 15 years of experience in Ge...
77,78,ID_WZHQK,I am a nurse working in a Sub-county Hospitals...
78,79,ID_ZHSMO,I am a nurse with 9 years of experience in Gen...
81,82,ID_VTRFF,I am a nurse with 12 years of experience in Ge...
82,83,ID_CWEIL,I am a nurse with 14 years of experience in Ge...
87,88,ID_MVXJK,I am a nurse with 24 years of experience in Ge...
88,89,ID_OPCIZ,I am a nurse with 15 years of experience in Ge...
90,91,ID_SCOBO,I am a nurse with 9 years of experience in Gen...
98,99,ID_SNZBL,I am a nurse with 18 years of experience in Ge...

In [6]:
# 9. Define a function to strip off the first sentence:
def remove_first_sentence(text):
    parts = text.split('. ', 1)
    if len(parts) > 1:
        return parts[1]
    else:
        # if there’s no period, return an empty string
        return ''

# 10. Apply that to the 'Prompt' column
df_filtered['Prompt'] = df_filtered['Prompt'].apply(remove_first_sentence)

In [7]:
#11. Print striped dataframe
df_filtered

,Original_Index,Master_Index,Prompt
2,3,ID_TYHSA,"A 22-year-old man, was brought in by the mothe..."
8,9,ID_UFAFI,23 year old is brought to the MCH clinic 10 da...
14,15,ID_OTEWX,A patient admitted from a peripheral facility ...
17,18,ID_ZQLND,A mother 4th day post delivery was brought to ...
18,19,ID_LXBDD,An 8-year-old boy was rushed to the ED with co...
20,21,ID_VJVBS,A 6-year-old male patient was admitted with a ...
21,22,ID_OZCVT,"A 40 year old lady, reports to the out-patient..."
22,23,ID_HBKUL,A 32-year-old male presents with complains of ...
29,30,ID_LWSTJ,A 50-year-old male patient comes in with hotne...
31,32,ID_NTHZR,A 15-year-old male patient is brought in with ...
32,33,ID_UAHZM,A 42 Year old para 2 + 0 gravida 3 came to the...
37,38,ID_ZNYCZ,A know hypertensive patient come with BP of 18...
38,39,ID_NCNYB,A 47-year-old man comes to the clinic with Hx ...
42,43,ID_JADVZ,A 65-year-old male client is brought in at eme...
68,69,ID_SKCAI,A 60 year old man brought to outpatient clinic...
73,74,ID_BFBYN,A 7-year-old boy came to the facility with cys...
74,75,ID_EISIY,An 18-year-old girl was brought by the mother ...
77,78,ID_WZHQK,"During a normal ANC visit,a 23 year old is don..."
78,79,ID_ZHSMO,A 4day old baby was brought to the hospital wi...
81,82,ID_VTRFF,A 25-year-old male presented to the emergency ...
82,83,ID_CWEIL,An eight-month-old child was brought to the ch...
87,88,ID_MVXJK,A 56-year-old male comes to the facility with ...
88,89,ID_OPCIZ,"A 5-year-old boy was rushed to the ED, having ..."
90,91,ID_SCOBO,A 30 year old woman presents with complaints o...
98,99,ID_SNZBL,A 48 year old was brought from theatre post th...

POTENTIAL PROBLEMS TO CHECK:

1.   SUSPECTED CONTEXT MISMATCH: 18
2.   SUSPECTED SPELLING ERRORS: 3,19,21,22,23,30,32,33,38,39,43,69,74,75,78,82,83,88,89,91,99
3.   SUSPECTED AGE MISMATCH: None