**TRAIN DATA**

---


This notebook unvails suspected errors in the training (train_raw.csv) dataset

**Please note that the 'Original_Index' column was started from 1 not 0**

In [ ]:
import pandas as pd

# 1. Load the original CSV
df = pd.read_csv('/content/train_raw.csv')

# 2. Keep only the three columns you care about
df_selected = df[['Master_Index', 'Prompt', 'Clinician']]

In [ ]:
# 3. List of row‐numbers (1‑based)
keep_1_based = [4,14,16,26,69,72,81,82,104,112,115,117,137,148,185,189,196,205,217,267,234,293,295,301,303,314,318,332,352,359,363,366,371,392,397]

In [ ]:
# 4. Convert to 0‑based positions for .iloc
keep_0_based = [i - 1 for i in keep_1_based]

# 5. Extract those rows (copying to avoid SettingWithCopyWarning)
df_filtered = df_selected.iloc[keep_0_based].copy()

# 6. Add a new column “Original_Index” that reflects the 1‑based row number
df_filtered['Original_Index'] = keep_1_based

# 7. Reorder columns so that Original_Index comes first
df_filtered = df_filtered[['Original_Index', 'Master_Index', 'Prompt', 'Clinician']]

In [ ]:
#8. Print dataframe
df_filtered

,Original_Index,Master_Index,Prompt,Clinician
3,4,ID_QOQTK,I am a nurse with 12 years of experience in Pr...,SUMMARY\n\n72-year-old female with inability t...
13,14,ID_IAYWV,I am a nurse with 15 years of experience in Ge...,Summary:\n3 year old male \nc/o- severe headac...
15,16,ID_CXPAN,I am a nurse with 1 years of experience in Gen...,Summary:\nA 65-year-old male presents with sev...
25,26,ID_OKDQA,I am a nurse working in a National Referral Ho...,Summary:\nA 70-year-old male has difficulty sw...
68,69,ID_IVWZD,I am a nurse with 10 years of experience in Ge...,A case of a 10-year-old female.\n\nComplaint: ...
71,72,ID_VZGOJ,I am a nurse working in a Dispensaries and Pri...,"College girl had amenorrhea, missed menses. Su..."
80,81,ID_JRROQ,I am a nurse with 10 years of experience in Ge...,3 year -Old male with complaints of undescende...
81,82,ID_KDYHM,I am a nurse with 12 years of experience in Ge...,Summary:\nA 24-year-old male presents with fev...
103,104,ID_MANPW,I am a nurse with 31 years of experience in Ge...,Summary:\na 60-year-old male presents with a t...
111,112,ID_WSHAY,I am a nurse working in a Health centres in Ka...,Complaint of:\nA 3½ year old child presenting ...
114,115,ID_KIPUQ,I am a nurse with 14 years of experience in Ge...,A 32 years old male brought to the clinic by t...
116,117,ID_IPRIH,I am a nurse with 15 years of experience in Me...,SUMMARY:\nA 28 year old patient is admitted wi...
136,137,ID_YTFNN,I am a nurse with 12 years of experience in Ge...,Summary:\nA 19-year-old male presents with aud...
147,148,ID_KHGYL,I am a nurse working in a Dispensaries and Pri...,Summary:\nA 26-year-old male presents to MTRH ...
184,185,ID_MWOML,I am a nurse with 26 years of experience in Ge...,3 years old baby with history of long prison i...
188,189,ID_KNXSI,I am a nurse with 30 years of experience in Ge...,Case summary\n64-year-old male with non-produc...
195,196,ID_KMGOO,I am a nurse working in a Dispensaries and Pri...,SUMMARY\nA 1 day old neonate in the postnatal ...
204,205,ID_REEBA,I am a nurse with 30 years of experience in Ge...,Summary:\nA 9-year-old girl at Kakamega Health...
216,217,ID_MGPFX,I am a nurse with 17 years of experience in Ge...,"Summary: Gravida 3, para 2 mother in acute lab..."
266,267,ID_GLHTL,I am a nurse working in a National Referral Ho...,Summary:\nA 32-year-old female presents with d...
233,234,ID_MOGWL,I am a nurse working in a Sub-county Hospitals...,A 40 year old female on chemotherapy at Kenyat...
292,293,ID_IKDJT,I am a nurse with 10 years of experience in Ge...,Summary:\nA 36 year old patient presents to th...
294,295,ID_OSNCH,I am a nurse with 1 years of experience in Gen...,Summary\nAn 8-day-old neonate presents with ab...
300,301,ID_XBCPB,I am a nurse with 27 years of experience in Ge...,Case Summary:\nA 20-year-old female presents w...
302,303,ID_OPORO,I am a nurse with 20 years of experience in Ge...,Summary\nA 14-year-old female with complaints ...
313,314,ID_YWXQL,I am a nurse with 10 years of experience in Ge...,SUMMARY:\n28 years old female post vaginal del...
317,318,ID_TYFAD,I am a nurse with 21 years of experience in Ge...,Summary:\nA 7-year-old girl presents with feve...
331,332,ID_QTNQH,I am a nurse working in a Dispensaries and Pri...,Summary:\nA 70-year-old female presents with p...
351,352,ID_VHRYD,I am a nurse with 12 years of experience in Ge...,Summary:\nA 60-year-old known diabetic woman p...
358,359,ID_HOISH,I am a nurse with 14 years of experience in Ge...,Summary:\nA 60 year old male brought to Sub Co...
362,363,ID_KPNYF,I am a nurse working in a Dispensaries and Pri...,Summary:\nA 34-year-old female presents with s...
365,366,ID_DBCXI,I am a nurse with 18 years of experience in Ge...,Summary:\nA 60-year-old male presents with a n...
370,371,ID_YVQUD,I am a nurse with 20 years of experience in Ge...,Summary:\nA 36-year-old male presents with sud...
391,392,ID_DWGSV,I am a nurse with 10 years of experience in Ge...,A 36 year old female with right knee replaceme...
396,397,ID_JNZVU,I am a nurse working in a National Referral Ho...,Summary:\nA 68-year-old male presents with fev...

In [ ]:
# 9. Define a function to strip off the first sentence:
def remove_first_sentence(text):
    parts = text.split('. ', 1)
    if len(parts) > 1:
        return parts[1]
    else:
        # if there’s no period, return an empty string
        return ''

# 10. Apply that to the 'Prompt' column
df_filtered['Prompt'] = df_filtered['Prompt'].apply(remove_first_sentence)

In [ ]:
#11. Print striped dataframe
df_filtered

,Original_Index,Master_Index,Prompt,Clinician
3,4,ID_QOQTK,"ER, aged 92 years, female was brought in with ...",SUMMARY\n\n72-year-old female with inability t...
13,14,ID_IAYWV,"So, a 30-year-old male was admitted in the war...",Summary:\n3 year old male \nc/o- severe headac...
15,16,ID_CXPAN,A 25-year-old man presents to the OPD with com...,Summary:\nA 65-year-old male presents with sev...
25,26,ID_OKDQA,A 46-year-old female was rushed into the emerg...,Summary:\nA 70-year-old male has difficulty sw...
68,69,ID_IVWZD,40 years old female was brought to hospital wi...,A case of a 10-year-old female.\n\nComplaint: ...
71,72,ID_VZGOJ,A college girl with severe abdominal pains. Mi...,"College girl had amenorrhea, missed menses. Su..."
80,81,ID_JRROQ,an 18 years old male came to the emergency dep...,3 year -Old male with complaints of undescende...
81,82,ID_KDYHM,"Sarah, ten years of age, presented to the emer...",Summary:\nA 24-year-old male presents with fev...
103,104,ID_MANPW,"A 69 yr old male presents at opd withfever,che...",Summary:\na 60-year-old male presents with a t...
111,112,ID_WSHAY,A three-year-old child is brought to OPD with ...,Complaint of:\nA 3½ year old child presenting ...
114,115,ID_KIPUQ,A 33 years old male is brought by a guardian t...,A 32 years old male brought to the clinic by t...
116,117,ID_IPRIH,A 26-year-old male patient is admitted with Bi...,SUMMARY:\nA 28 year old patient is admitted wi...
136,137,ID_YTFNN,A 3 year old female is brought with complaints...,Summary:\nA 19-year-old male presents with aud...
147,148,ID_KHGYL,A 30 year old man was brought by relatives wit...,Summary:\nA 26-year-old male presents to MTRH ...
184,185,ID_MWOML,A three-year-old baby came to outpatient depar...,3 years old baby with history of long prison i...
188,189,ID_KNXSI,A 64 year old man came to the facility with a ...,Case summary\n64-year-old male with non-produc...
195,196,ID_KMGOO,A 1/7old neonate in postnatal ward is drooling...,SUMMARY\nA 1 day old neonate in the postnatal ...
204,205,ID_REEBA,I have received a girl who is eight years old ...,Summary:\nA 9-year-old girl at Kakamega Health...
216,217,ID_MGPFX,A mother who is being managed in an active pha...,"Summary: Gravida 3, para 2 mother in acute lab..."
266,267,ID_GLHTL,"A 40-year old mother, para 4+1 G 6, during del...",Summary:\nA 32-year-old female presents with d...
233,234,ID_MOGWL,A 60 year old lady comes to the facility for f...,A 40 year old female on chemotherapy at Kenyat...
292,293,ID_IKDJT,A 36 year old is in the emergency c/o severe a...,Summary:\nA 36 year old patient presents to th...
294,295,ID_OSNCH,A 6-day-old male neonate is brought by her mot...,Summary\nAn 8-day-old neonate presents with ab...
300,301,ID_XBCPB,A 20-year-old Female patient came to the clini...,Case Summary:\nA 20-year-old female presents w...
302,303,ID_OPORO,A 40-year-old female complains of chest tightn...,Summary\nA 14-year-old female with complaints ...
313,314,ID_YWXQL,A 26 years old female post delivering. SVD. Ve...,SUMMARY:\n28 years old female post vaginal del...
317,318,ID_TYFAD,A patient comes in the outpatient clinic with ...,Summary:\nA 7-year-old girl presents with feve...
331,332,ID_QTNQH,A middle-aged mother came to our facility with...,Summary:\nA 70-year-old female presents with p...
351,352,ID_VHRYD,A para 0 +0 gravida 1 mother comes to MCH for ...,Summary:\nA 60-year-old known diabetic woman p...
358,359,ID_HOISH,A 67 yrs old male brought to health facility w...,Summary:\nA 60 year old male brought to Sub Co...
362,363,ID_KPNYF,A mother comes to the CWC clinic for growth mo...,Summary:\nA 34-year-old female presents with s...
365,366,ID_DBCXI,A 25 year old male presents with a 5-day histo...,Summary:\nA 60-year-old male presents with a n...
370,371,ID_YVQUD,An 8-year-old is brought to the hospital by th...,Summary:\nA 36-year-old male presents with sud...
391,392,ID_DWGSV,A 66 years old female is in the orthopaedic wa...,A 36 year old female with right knee replaceme...
396,397,ID_JNZVU,"A 38 yr old para 3, presented to clinic with c...",Summary:\nA 68-year-old male presents with fev...

POTENTIAL PROBLEMS TO CHECK:

1.   SUSPECTED CONTEXT MISMATCH: 26,104,137,148,161,318,332,352,363,371,397
2.   SUSPECTED SPELLING ERRORS: 112,185,189,280,284,286,289
3.   SUSPECTED AGE MISMATCH: 4,14,26,69,72,81,82,104,115,117,137,148,163,168,161,280,284,289,359,363,366,371,392,397