INSTALL LIBRARIES

In [1]:
!pip install transformers datasets pandas torch rouge_score sentencepiece

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.53.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (2.14.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/dist-packages (0.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.7)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec>=2021.11.1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.11.1->datasets) (2025.3.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.14.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.20.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.7.9)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (1.5.1)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.6 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 62.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 36.5 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 42.6 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.5 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.7 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 7.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 37.5 MB/s eta 0:00:00
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=ad6aaf967213c6573db87f29185ffa460a3b0b90846c3e6c89f0b4646988a4c9
  Stored in directory: /root/.cache/pip/wheels/1e/19/43/8a442dc83660ca25e163e1bd1f89919284ab0d0c1475475148
Successfully built rouge_score
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, rouge_score, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 rouge_score-0.1.2

In [2]:
!pip install accelerate

Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.8.1)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.11/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (2.6.0+cu124)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (0.33.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from accelerate) (0.5.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.1.5)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2025.7.9)

In [3]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.5-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.14.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.15)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.2)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.33.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.15)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (3.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.7.9)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.5-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.6 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.5

IMPORT LIBRARIES

In [4]:
import os
import pandas as pd
import numpy as np
import string
import re
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    MvpTokenizer,
    MvpForConditionalGeneration,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    GenerationConfig,#########
    EarlyStoppingCallback,
)
from evaluate import load as load_metric

In [5]:
# import os
# import pandas as pd
# import numpy as np
# import string
# import re
# import torch
# from datasets import Dataset, DatasetDict, load_metric
# from transformers import (
#     MvpTokenizer,
#     MvpForConditionalGeneration,
#     DataCollatorForSeq2Seq,
#     Seq2SeqTrainingArguments,
#     Seq2SeqTrainer,
#     GenerationConfig,#########
#     EarlyStoppingCallback,
# )

REMOVE MARKERS FUNCTION

*   Removes markers
*   Strip whitespace

In [6]:

def clean_tagged_dataframe(
    df: pd.DataFrame,
    cols_to_clean: list = ["source", "target"],
    tags: list = None
) -> pd.DataFrame:
    """
    Remove predefined tags from specified text columns in a DataFrame.

    Args:
        df (pd.DataFrame): Input DataFrame.
        cols_to_clean (list of str): Column names to clean (default ["source","target"]).
        tags (list of regex strings): Tags to remove. If None, defaults to:
            [r'\[INTRO\]', r'\[QUES\]', r'\[VITALS\]', r'\[HIST\]', r'\[SYM\]'].

    Returns:
        pd.DataFrame: A copy of the DataFrame with the specified columns cleaned.
    """
    # Default tags if none provided
    if tags is None:
        tags = [r'\[INTRO\]',r'\[INRO\]', r'\[QUES\]', r'\[VITALS\]', r'\[HIST\]', r'\[SYM\]']
    pattern = "|".join(tags)

    df_clean = df.copy()
    cleaned_any = False

    for col in cols_to_clean:
        if col in df_clean.columns:
            # ensure text, strip tags & whitespace
            df_clean[col] = (
                df_clean[col]
                .astype(str)
                .str.replace(pattern, "", regex=True)
                .str.strip()
            )
            cleaned_any = True

    if not cleaned_any:
        raise ValueError(
            f"None of the columns {cols_to_clean} found in DataFrame. "
            f"Found columns: {list(df_clean.columns)}"
        )

    return df_clean

CLEAN TEXT FUNCTION


*   Removes unwanted items
*   Removes non-alphanumeric characters

In [7]:

def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""
    text = text.lower()
    # Replace '-' with a space
    text = text.replace("-", " ")
    text = text.replace("/", " ")
    text = text.replace("+", " ")
    text = text.replace("?", " ")
    text = text.replace("!", " ")
    text = text.replace(",", " ")
    text = text.replace(":", " ")
    text = text.replace(";", " ")
    text = text.replace("?"," ")
    text = text.replace("%", " ")
    text = text.replace("*"," ")
    text = text.replace("°C"," ")
    text = text.replace("."," ")
    # Remove punctuation
    translator = str.maketrans("", "", string.punctuation)
    text = text.translate(translator)
    # Remove any other non-alphanumeric characters
    text = re.sub(r"[^a-z0-9\s]", "", text)
    # Collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text

LOAD DATA


*   Load datasets
*   Preview dataframes

In [9]:
# 1. Load data
train_df = pd.read_csv("/content/extracted_marker_train_json_data_clean.csv").dropna(subset=["source","target"]).reset_index(drop=True)
test_df  = pd.read_csv("/content/extracted_marker_test_json_data_clean.csv").dropna(subset=["source"]).reset_index(drop=True)

In [10]:
train_df = clean_tagged_dataframe(train_df)
test_df = clean_tagged_dataframe(test_df)

In [11]:
train_df

,source,target
0,A 4-year-old child presents to the emergency d...,Summary:\nA 4 year old with 5% superficial bur...
1,A 6 year old girl presented to the emergency d...,Summary\n6-year-old present with vomiting and ...
2,"Forty-seven years, old man, came to Casualty, ...",Summary\nA 47-year-old man presents with sever...
3,"ER, aged 72 years, female was brought in with...",SUMMARY\n\n72-year-old female with inability t...
4,A 22-year-old female patient is brought in wi...,"A 22 year old female presents with headache, d..."
...,...,...
400,A 48 years old lady was admitted with complain...,Summary\n48-year-old female admitted with easy...
401,A 25-year-old man presents to the OPD with com...,SUMMARY\n25 yr old man with known rheumatic he...
402,"A 69 yr old male presents at opd with fever, ...","SUMMARY\n69-year-old male with fever, chest pa..."
403,A 3 year old female is brought with complaints...,SUMMARY\n3-year-old female with increased thir...
404,"A 32-year old mother, para 4+1 G 6, during del...","SUMMARY\n32-year-old mother, para 4+1 G6, duri..."

In [12]:
test_df

                                               source
0   A 24 year old female complains of sharp pain i...
1   A 3 years old boy was brought to the facility,...
2   A 22-year-old man,  was brought in by the moth...
3   A 6 years old girl is brought to Opd with  his...
4   So, I was in the MCH clinic in the morning. I ...
..                                                ...
95  A child 6 years of age came to the clinic acco...
96  A 49-year-old lady presented at the facility w...
97  A 35 year old man comes to the outpatient depa...
98  A 48 year old was brought from theatre post th...
99  A 58-year-old patient come to outpatient depar...

[100 rows x 1 columns]

In [13]:
test_df['source'] = test_df['source'].str.replace(r"[-\n]", " ", regex=True)
train_df['source'] = train_df['source'].str.replace(r"[-\n]", " ", regex=True)
train_df['target'] = train_df['target'].str.replace(r"[-\n]", " ", regex=True)

In [14]:
train_df

,source,target
0,A 4 year old child presents to the emergency d...,Summary: A 4 year old with 5% superficial burn...
1,A 6 year old girl presented to the emergency d...,Summary 6 year old present with vomiting and a...
2,"Forty seven years, old man, came to Casualty, ...",Summary A 47 year old man presents with severe...
3,"ER, aged 72 years, female was brought in with...",SUMMARY 72 year old female with inability to ...
4,A 22 year old female patient is brought in wi...,"A 22 year old female presents with headache, d..."
...,...,...
400,A 48 years old lady was admitted with complain...,Summary 48 year old female admitted with easy ...
401,A 25 year old man presents to the OPD with com...,SUMMARY 25 yr old man with known rheumatic hea...
402,"A 69 yr old male presents at opd with fever, ...","SUMMARY 69 year old male with fever, chest pai..."
403,A 3 year old female is brought with complaints...,SUMMARY 3 year old female with increased thirs...
404,"A 32 year old mother, para 4+1 G 6, during del...","SUMMARY 32 year old mother, para 4+1 G6, durin..."

In [15]:
test_df

                                               source
0   A 24 year old female complains of sharp pain i...
1   A 3 years old boy was brought to the facility,...
2   A 22 year old man,  was brought in by the moth...
3   A 6 years old girl is brought to Opd with  his...
4   So, I was in the MCH clinic in the morning. I ...
..                                                ...
95  A child 6 years of age came to the clinic acco...
96  A 49 year old lady presented at the facility w...
97  A 35 year old man comes to the outpatient depa...
98  A 48 year old was brought from theatre post th...
99  A 58 year old patient come to outpatient depar...

[100 rows x 1 columns]

TRAIN TEST SPLIT

*   Split Test data
*   Split Train data

In [16]:
from sklearn.model_selection import train_test_split

# Split train_df into train and test parts
train, test = train_test_split(
    train_df,
    test_size=0.2,        # 20% goes to test_df
    random_state=42,      # for reproducibility
    shuffle=True          # shuffle before splitting (default)
)

CONVERT DATAFRAMES INTO HUGGINGFACE DATASET FORMAT

In [17]:
hf_train = Dataset.from_pandas(train)
hf_test  = Dataset.from_pandas(test)

LOAD MODEL AND TOKENIZER

In [18]:
# 2. Tokenizer & Model
tokenizer = MvpTokenizer.from_pretrained("RUCAIBox/mvp")
model     = MvpForConditionalGeneration.from_pretrained("RUCAIBox/mtl-data-to-text")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/27.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/41.0 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/908 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/908 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

CHECK MAXIMUM TOKEN COUNT IN SOURCE AND TAGET OF TRAIN/TEST

In [20]:
# from transformers import AutoTokenizer

# # Load the tokenizer you're using
# tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")

# Count tokens per example
train_df['source_token_count'] = train_df['source'].apply(lambda x: len(tokenizer.encode(x, truncation=False)))
train_df['target_token_count'] = train_df['target'].apply(lambda x: len(tokenizer.encode(x, truncation=False)))

# Get maximums
max_source_length = train_df['source_token_count'].max()
max_target_length = train_df['target_token_count'].max()

print(f"Max source length: {max_source_length} tokens")
print(f"Max target length: {max_target_length} tokens")

Max source length: 291 tokens
Max target length: 500 tokens

In [21]:
# Count tokens per example
test_df['source_token_count'] = test_df['source'].apply(lambda x: len(tokenizer.encode(x, truncation=False)))

# Get maximums
max_source_length_t = test_df['source_token_count'].max()

print(f"Max source length: {max_source_length_t} tokens")

Max source length: 275 tokens

In [18]:
# max_input_length  = 512 #512
# max_output_length = 256  #256 #128 # 256

SET MAXIMUM TOKEN: INPUT AND OUTPUT LENGTH

In [22]:
max_input_length  = 384    # >291, so no source will be truncated
max_output_length = 512    # covers your 500-token targets

PREPROCESSING FUNCION

In [23]:
# 3. Preprocessing fn
def preprocess_fn(batch):
    inputs = tokenizer(
        batch["source"],
        truncation=True,
        max_length=max_input_length,
        padding="max_length",
    )
    targets = tokenizer(
        batch["target"],
        truncation=True,
        max_length=max_output_length,
        padding="max_length",
    ) if "target" in batch else {}
    labels = targets.get("input_ids", None)
    # replace pad token id's in labels by -100 so they are ignored by loss
    if labels is not None:
        labels = [
            [(l if l != tokenizer.pad_token_id else -100) for l in lab]
            for lab in labels
        ]
    return {
        **inputs,
        **({"labels": labels} if labels is not None else {}),
    }

In [20]:
# 4. Prepare tokenized datasets
# tokenized_datasets = DatasetDict({
#     "train": hf_train.map(preprocess_fn, batched=True, remove_columns=hf_train.column_names),
#     "eval":  hf_train.shuffle().select(range(100)).map(preprocess_fn, batched=True, remove_columns=hf_train.column_names),
# })

APPLY PREPROCESSING FUNCTION

In [24]:
# from datasets import DatasetDict

tokenized_datasets = DatasetDict({
    "train": hf_train.map(
        preprocess_fn,
        batched=True,
        remove_columns=hf_train.column_names
    ),
    "eval": hf_test.map(
        preprocess_fn,
        batched=True,
        remove_columns=hf_test.column_names
    ),
})

Map:   0%|          | 0/324 [00:00<?, ? examples/s]

Map:   0%|          | 0/81 [00:00<?, ? examples/s]

DATA COLLATOR

In [25]:
# 5. Data collator
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

ROUGE METRIC

In [26]:
# 6. Load ROUGE
rouge = load_metric("rouge")

Downloading builder script: 0.00B [00:00, ?B/s]

ROUGE METRIC FUNCTION

In [27]:


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in predictions]
    result["gen_len"] = np.mean(prediction_lens)

    return {k: round(v, 4) for k, v in result.items()}

CUDA CLEAR CACHE


*   Had a few memory issues
*   Did not have good resources

In [28]:
import torch
torch.cuda.empty_cache()

In [27]:
# training_args = Seq2SeqTrainingArguments(
#     # ← your generation settings bundled here
#     generation_config=GenerationConfig(
#         decoder_start_token_id=tokenizer.pad_token_id,
#         max_length=512,           # allow up to 512 tokens in the answer
#         min_length=256,           # ensure at least 128 tokens are produced
#         length_penalty=1.2,       # discourage too-short outputs
#         num_beams=4,              # use beam search for more coherent long output
#         no_repeat_ngram_size=3,   # avoid repeating the same 3-gram
#         early_stopping=True,      # stop once all beams finish
#     ),

#     output_dir="mvp-models",

#     # → epoch-based evaluation & checkpointing
#     eval_strategy="epoch",    # run eval at the end of each epoch
#     save_strategy="epoch",          # save a checkpoint at the end of each epoch
#     logging_strategy="epoch",
#     load_best_model_at_end=True,    # after training, reload the best checkpoint on your metric
#     metric_for_best_model="eval_rouge1",  # or whichever ROUGE key you prefer
#     greater_is_better=True,              # for ROUGE f‑scores

#     per_device_train_batch_size=4,
#     per_device_eval_batch_size=4,
#     gradient_accumulation_steps=4,  # or more
#     learning_rate=5e-5,
#     weight_decay=0.01,
#     num_train_epochs=20,

#     predict_with_generate=True,         # enable generation during eval
#     #generation_max_length=512,          # passed to model.generate()
#     #generation_num_beams=4,             # passed to model.generate()
#     #fp16=True,                          # if you have a GPU
#     push_to_hub=False,
#     report_to="none",
#     #torch_compile=False,           # disable torch.compile calls inside Trainer
# )

SEQ2SEQ TRAIN ARGS SETUP

In [29]:
training_args = Seq2SeqTrainingArguments(

    generation_config=GenerationConfig(
        decoder_start_token_id=tokenizer.pad_token_id,
        max_length=512,           # allow up to 512 tokens in the answer
        min_length=256,           # *256 ensure at least 256 tokens are produced
        length_penalty=1.2,       # discourage too-short outputs
        num_beams=4,              # use beam search for more coherent long output
        no_repeat_ngram_size=3,   # avoid repeating the same 3-gram
        early_stopping=True,      # stop once all beams finish
    ),

    # → epoch-based evaluation & checkpointing
    eval_strategy="steps",    # run eval at the end of each epoch
    save_strategy="steps",          # save a checkpoint at the end of each epoch
    logging_strategy="steps",
    output_dir="model-mvp",
    load_best_model_at_end=True,    # after training, reload the best checkpoint on your metric
    eval_steps=500,
    logging_steps=100,
    save_steps=500,
    save_total_limit=2,
    metric_for_best_model="eval_rouge1",  # or whichever ROUGE key you prefer
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    learning_rate=5e-5,
    weight_decay=0.01,
    num_train_epochs=20,

    predict_with_generate=True,         # enable generation during eval
    #generation_max_length=512,          # passed to model.generate()
    #generation_num_beams=4,             # passed to model.generate()
    #fp16=True,                          # if you have a GPU
    push_to_hub=False,
    report_to="none",

)

In [30]:
# 8. Trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset= tokenized_datasets["eval"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,     # use ROUGE
    callbacks=[
        EarlyStoppingCallback(early_stopping_patience=5, early_stopping_threshold=0.001)
    ]
)

/tmp/ipython-input-30-1533709742.py:2: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

ENABLE MODEL GRADIENT CHECKPOINTING

In [31]:
model.gradient_checkpointing_enable()  # at model instantiation

TRAIN MODEL

In [32]:
# 9. Train + evaluate
trainer.train()
# during evaluation steps, trainer will:
#   * call model.generate(...) with your beam/length settings
#   * compute ROUGE on the generated outputs

/usr/local/lib/python3.11/dist-packages/transformers/modeling_utils.py:3685: UserWarning: Moving the following attributes in the config to the generation config: {'early_stopping': True, 'num_beams': 5, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(
There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

TrainOutput(global_step=820, training_loss=1.2859045970730665, metrics={'train_runtime': 3557.622, 'train_samples_per_second': 1.821, 'train_steps_per_second': 0.23, 'total_flos': 5266064183132160.0, 'train_loss': 1.2859045970730665, 'epoch': 20.0})

METRICS

In [ ]:
# 10. Final evaluation on held-out eval split
metrics = trainer.evaluate()
print("Eval metrics:", metrics)

APPLY PREDICTIONS ON TEST DATAFRAME

In [ ]:
# 11. Inference on test set
model.eval()
all_preds = []
batch_size = 8
for i in range(0, len(test_df), batch_size):
    batch_src = test_df["source"].iloc[i : i + batch_size].tolist()
    inputs = tokenizer(
        batch_src,
        return_tensors="pt",
        truncation=True,
        max_length=max_input_length,
        padding="longest",
    ).to(trainer.args.device)

    generated_ids = model.generate(
        inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_length=256,           # match your target length
        min_length=80,            # avoid too‑short outputs
        length_penalty=1.2,       # encourage full summarization
        num_beams=10,              # more thorough search
        no_repeat_ngram_size=3,   # reduce loops
        early_stopping=True,
        bad_words_ids=[[tokenizer.encode(w)[0]] for w in ["basically", "actually", "..."]]
    )
    preds = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
    all_preds.extend(preds)

TRAIN TESTING

In [53]:
import numpy as np
from evaluate import load as load_metric

# Only take first 5 examples
subset_df = train_df.iloc[:4]

model.eval()
all_preds_train = []
batch_size = 8

for i in range(0, len(subset_df), batch_size):
    batch_src = subset_df["source"].iloc[i : i + batch_size].tolist()
    inputs = tokenizer(
        batch_src,
        return_tensors="pt",
        truncation=True,
        max_length=max_input_length,
        padding="longest",
    ).to(trainer.args.device)

    # generated_ids = model.generate(
    #     inputs["input_ids"],
    #     attention_mask=inputs["attention_mask"],
    #     max_length=512,
    #     min_length=256,
    #     length_penalty=1.2,
    #     num_beams=4,
    #     no_repeat_ngram_size=3,
    #     early_stopping=True,
    # )

    generated_ids = model.generate(
        inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_length=256,           # match your target length
        min_length=80,            # avoid too‑short outputs
        length_penalty=1.2,       # encourage full summarization
        num_beams=10,              # more thorough search
        no_repeat_ngram_size=3,   # reduce loops
        early_stopping=True,
        bad_words_ids=[[tokenizer.encode(w)[0]] for w in ["basically", "actually", "..."]]
    )

    preds_train = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
    all_preds_train.extend(preds_train)

# Now all_preds_train contains your 5 generated summaries
for idx, (src, pred) in enumerate(zip(subset_df["source"], all_preds_train), 1):
    print(f"Example {idx}\nSource: {src}\nGenerated: {pred}\n{'-'*60}")

Example 1
Source: A 4 year old child presents to the emergency department with second degree burns on the forearm after accidentally touching a hot stove. The child was playing in the kitchen when they reached out to touch the stove.  The burns cover about 5% of the total body surface area. The child is alert and crying, with redness, blisters, and swelling on the affected area. The burns appear to be superficial to moderate in severity. The child is in mild pain, and there is no indication of airway or breathing distress.  No other injuries are noted.  Questions: 1. What is the immediate treatment protocol for second degree burns in paediatric patients? 2. Should any tetanus prophylaxis be considered in this case? 3. What follow up care should be recommended for burn healing?
Generated: Summary A 4 year old child presents with second degree burns on the forearm after accidentally touching a hot stove. The burns cover about 5% of the body surface area and are superficial to moderate in severity. The child is alert and crying, with redness, blisters, and swelling on the affected area. No other injuries noted.  Dx: Second degree burn in a child   Ddx: Intracranial burn   Management:  Start the patient on oxygen therapy if the child is in respiratory distress.  Administer tetanus prophylaxis if tetanus toxoid screening is not available.  Apply pressure dressing to the burn site to prevent further spread.  Admit the patient and continue with the above as you monitor the patient’s response.  Follow up care should be recommended for burn healing:  Antibiotics such as ceftriaxone and metronidazole.  Analgesics for pain relief such as paracetamol.  Anticonvulsants such as ibuprofen can also be given to help with pain relief. refer to a pediatrician for further review and further management referral pediatricians are often reluctant to admit children due to risk of complications
------------------------------------------------------------
Example 2
Source: A 6 year old girl presented to the emergency department  with complaints of vomiting and abdominal pains. Patient is known diabetic on insulin and does not take as scheduled because of lack of funds. On assessment the girl is confused, having Kussmaul breathing and fruity scented breath. Has dry tongue and reports blurred vision.  Temp 37, Pulse 120b/m, Resp 48b/m rapid and labored, SPO2 90% on room air.  Questions What is the diagnosis of the patient? What is the most immediate management? What health education will be given to the patient and family? Which investigations will be ordered?
Generated: Summary 6 year old presents with vomiting and abdominal pains. Known diabetic on insulin but doesn’t take it as scheduled due to lack of funds. He is confused, Kussmaul breathing, fruity scented breath, dry tongue and blurry vision. Vitals: Temp   37°C, pulse   120 b/min, RR   48 b/m, rapid laboured SpO₂ 90% on room air  Diagnosis: Diabetic Ketoacidosis (DKA)  Differential Diagnoses: Hyperglycemic hyperosmolar state Diabetic ketoacidosis Hyperemesis gravidarum Gastroenteritis  Management: 1. Insert catheter to monitor input and output 2. Give IV fluids to control fluid overload 3. Give analgesics for pain 4. Call physician and request urgent review 5. Call for urgent general surgery review 6. Refer to Intravenous labetalol for monitoring and further management 7. Start IV antihypertensive e.g. dexamethasone 8. Monitor glucose levels with a target pH of 8.5   Investigations: Complete blood count Urea, electrolytes and creatinines Liver function tests Random blood sugar C reactive protein
------------------------------------------------------------
Example 3
Source: Forty seven years, old man, came to Casualty, supported by two men, screaming, because of pain. Upon inquiry, he reported that he had  severe abdominal pain, upper abdominal pain, in the gastric area, which had started the previous night.  He had not slept. He also reported that this was not the first time that it was happening, and he reported a history of peptic ulcer disease. This time it was severe.   So on observations, the PUDs were, the  vitals were within normal range.  The questions I had were, an analgesic first? or this patient was sent for labs? or to do a scan first?
Generated: Summary A 47 year old man presents with severe upper abdominal pain in the gastric area that started the previous night. He has a history of peptic ulcer disease. Vitals are normal. Patient is in distress. Problems: Severe pain Distress inability to sleep Management: Administer analgesia for the severe pain. Start IV fluids to correct possible volume depletion. Administer proton pump inhibitor for the gastrointestinal upset. Start broad spectrum antibiotics empirically. Refer urgently to a facility with gastroenterology expertise for further management. Investigations: Full hemogram Urea, electrolytes and creatinines Liver function tests Peripheral blood film Stool for occult blood Causes: Pneumonia Acute pancreatitis) Diagnosis: Acute Acute Pulmonary Respiratory Tract Infection) Definitive management depends on the diagnosis. If the diagnosis is confirmed, manage with antibiotics e.g. ceftriaxone and metronidazole. If not, refer for urgent general surgery.) Do a scan to check for features of peritonitis.  Radiology: Abdominal pelvic ultrasound to assess for air fluid levels. Erect abdominal x ray to look for air under the diaphragm to rule out space occupying lesions
------------------------------------------------------------
Example 4
Source: ER, aged 72 years, female was brought in  with inability to walk, abdominal pain, generalized body malaise and history of fecal impaction.  On assessment she is sick with GCS of 4/15. BP 131/82mmHg, MAP 96 , HR 92, RR 17b/min, Temp 36.3, SP02 68%.  Questions: What emergency care should patient ER receive? What investigation should be done? What is the diagnosis?
Generated: SUMMARY 72 year old female with inability to walk, abdominal pain, generalized body malaise and history of fecal impaction. On exam GCS is 15/15 (tachycardic)  Differential Diagnosis  Acute appendicitis   What emergency care should patient receive? Analgesics for pain Antibiotics such as ceftriaxone Antispasmodics such as ibuprofen  Laboratory investigations: Full hemogram Urea, electrolytes and creatinines Liver function tests Complete blood count C reactive protein Erythrocyte sedimentation rate Stool for occult blood Colonoscopy Abdominal pelvic ultrasound Erect abdominal x ray  What is the diagnosis? Fibroenteritis Appendicitis Malaisepyramidal illnessictractic encephalopathyneumothorax   Hepatocellular carcinoma Sputum for ova, cyst and omphalogranuloma urea, creatinine and electrolytes Liver function test CBC  What investigations should be done? Laboratory tests: full hemogram to check for levels of HB, UECs, CRP, LFTs, coagulation profile to check
------------------------------------------------------------

In [41]:
# 2. Prepare references
references = train_df["target"].tolist()

# 3. Compute ROUGE
rouge = load_metric("rouge")
rouge_res = rouge.compute(
    predictions=all_preds_train,
    references=references,
    use_stemmer=True
)
# extract F‑scores ×100
rouge_scores = {f"rouge_{k}": v * 100 for k, v in rouge_res.items()}

# 4. Exact‑Match Accuracy
exact_matches = [p.strip() == r.strip() for p, r in zip(all_preds_train, references)]
exact_match = 100.0 * sum(exact_matches) / len(exact_matches)

# 5. Token‑Level Accuracy
correct_tokens = 0
total_tokens   = 0
for p, r in zip(all_preds_train, references):
    p_toks = tokenizer.tokenize(p)
    r_toks = tokenizer.tokenize(r)
    L = min(len(p_toks), len(r_toks))
    correct_tokens += sum(pt == rt for pt, rt in zip(p_toks, r_toks))
    total_tokens   += max(len(r_toks), 1)

token_accuracy = 100.0 * correct_tokens / total_tokens

# 6. Ratio of Exact‑Match to Token Accuracy
ratio_em_to_ta = exact_match / token_accuracy

# 7. Print everything
print(f"ROUGE scores: {rouge_scores}")
print(f"Exact‑Match Accuracy: {exact_match:.2f}%")
print(f"Token‑Level Accuracy: {token_accuracy:.2f}%")
print(f"EM / Token‑Acc ratio: {ratio_em_to_ta:.4f}")

ROUGE scores: {'rouge_rouge1': np.float64(33.61123235701714), 'rouge_rouge2': np.float64(20.110621841434956), 'rouge_rougeL': np.float64(25.240889232033403), 'rouge_rougeLsum': np.float64(25.22692247931846)}
Exact‑Match Accuracy: 0.00%
Token‑Level Accuracy: 10.04%
EM / Token‑Acc ratio: 0.0000

In [46]:
train_df['Target_Compare']  = all_preds_train

In [47]:
train_df[['target','Target_Compare']]

,target,Target_Compare
0,Summary: A 4 year old with 5% superficial burn...,Summary A 4 year old child presents with secon...
1,Summary 6 year old present with vomiting and a...,Summary 6 year old presents with vomiting and ...
2,Summary A 47 year old man presents with severe...,Summary A 47 year old man presents with severe...
3,SUMMARY 72 year old female with inability to ...,SUMMARY 72 year old female with inability to w...
4,"A 22 year old female presents with headache, d...",Summary A 22 year old female presents with hea...
...,...,...
400,Summary 48 year old female admitted with easy ...,"SUMMARY 48 year old with easy fatigability, le..."
401,SUMMARY 25 yr old man with known rheumatic hea...,Summary: 25 year old man with a history of run...
402,"SUMMARY 69 year old male with fever, chest pai...","SUMMARY 69 yr old male with fever, chest pains..."
403,SUMMARY 3 year old female with increased thirs...,Summary 3 year old female with complaints of i...
404,"SUMMARY 32 year old mother, para 4+1 G6, durin...","SUMMARY 32 year old mother, para 4+1 G6, durin..."

GENERATE SUBMISSION FILE

In [36]:
test_raw_df = pd.read_csv('/content/test_raw.csv')

master_index = test_raw_df[['Master_Index']]

master_index

   Master_Index
0      ID_CUAOY
1      ID_OGSAY
2      ID_TYHSA
3      ID_CZXLD
4      ID_ZJQUQ
..          ...
95     ID_AYCAI
96     ID_CLEYN
97     ID_BRIIW
98     ID_SNZBL
99     ID_KXLGG

[100 rows x 1 columns]

In [50]:
# 12. Export submission
submission = test_df.copy()
submission["Clinician"] = all_preds
submission["Master_Index"] = master_index['Master_Index']

submission = submission[["Master_Index","Clinician"]]
submission.to_csv("test_submission_tests.csv", index=False)
print("Saved submission.csv with", len(submission), "rows.")

Saved submission.csv with 100 rows.

In [35]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive

In [38]:
# !cp -r /content/model-mvp /content/drive/MyDrive/

In [ ]:
# import shutil

# # Define source and destination paths
# src = "/content/model-mvp"
# dst = "/content/drive/MyDrive/model-mvp"

# # Copy entire directory tree
# shutil.copytree(src, dst)